name: release

on:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: DND-IT/tamci/actions/release@ed90491bdd4f77b7423fdbb151ad107ca4b4c6e2 # v0.2.2
        with:
          tag-prefix: v
